import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { ArrowDownToLine, ArrowLeft, ArrowUpFromLine, CalendarRange, FileSpreadsheet, Pencil, Plus, Trash2, X } from 'lucide-react-native';
import { useState } from 'react';
import { Alert, FlatList, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { apiErrorMessage } from '../api/client';
import { endpoints } from '../api/endpoints';
import type { Sprint } from '../api/types';
import { useAuth } from '../auth/AuthProvider';
import { PageHeader } from '../components/PageHeader';
import { PrimaryButton } from '../components/PrimaryButton';
import { Screen } from '../components/Screen';
import { EmptyState, ErrorState, LoadingState } from '../components/StateView';
import { useAppTheme } from '../theme';

export function ProjectSprintsScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const projectId = Number(id);
  const theme = useAppTheme();
  const router = useRouter();
  const queryClient = useQueryClient();
  const { user } = useAuth();
  const writable = !user?.demo_account && Boolean(user?.permissions?.includes('projects.manage'));
  const [editing, setEditing] = useState<Sprint | null | undefined>(undefined);
  const project = useQuery({ queryKey: ['project', projectId], queryFn: () => endpoints.project(projectId), enabled: Number.isFinite(projectId) });
  const sprints = useQuery({ queryKey: ['project-sprints', projectId], queryFn: () => endpoints.sprints(projectId), enabled: Number.isFinite(projectId) });
  const refresh = async () => { setEditing(undefined); await queryClient.invalidateQueries({ queryKey: ['project-sprints', projectId] }); await queryClient.invalidateQueries({ queryKey: ['project', projectId] }); };
  const importBacklog = useMutation({ mutationFn: () => endpoints.importBacklog(projectId), onSuccess: async () => { await refresh(); Alert.alert('Backlog imported', 'Tasks were refreshed from the connected sheet.'); }, onError: (error) => Alert.alert('Unable to import backlog', apiErrorMessage(error)) });

  return <Screen header={<PageHeader leading={<Pressable accessibilityLabel="Back" onPress={() => router.back()} style={styles.iconButton}><ArrowLeft color={theme.text} size={22} /></Pressable>} title="Sprints" subtitle={project.data?.name || 'Iterations and backlog'} action={writable ? <Pressable accessibilityLabel="Create sprint" onPress={() => setEditing(null)} style={[styles.add, { backgroundColor: theme.primary }]}><Plus color="#ffffff" size={21} /></Pressable> : undefined} />}>
    {writable && project.data?.sheet_integration_enabled ? <Pressable accessibilityLabel="Import backlog from sheet" disabled={importBacklog.isPending} onPress={() => importBacklog.mutate()} style={[styles.sheetAction, { backgroundColor: theme.surface, borderColor: theme.border }]}><FileSpreadsheet color={theme.primary} size={19} /><View style={styles.flex}><Text style={[styles.actionTitle, { color: theme.text }]}>Import backlog</Text><Text style={[styles.actionMeta, { color: theme.textMuted }]}>{project.data.sheet_id ? 'Connected project sheet' : 'Sheet ID is not configured'}</Text></View><ArrowDownToLine color={theme.textMuted} size={18} /></Pressable> : null}
    {sprints.isLoading || project.isLoading ? <LoadingState label="Loading sprints" /> : null}
    {sprints.isError || project.isError ? <ErrorState message={apiErrorMessage(sprints.error || project.error)} onRetry={() => Promise.all([sprints.refetch(), project.refetch()])} /> : null}
    {sprints.data ? <FlatList contentContainerStyle={styles.list} data={sprints.data} keyExtractor={(item) => String(item.id)} onRefresh={() => sprints.refetch()} refreshing={sprints.isRefetching} ListEmptyComponent={<EmptyState title="No sprints" message="Create a delivery window or keep tasks in the backlog." />} renderItem={({ item }) => <Pressable accessibilityRole={writable ? 'button' : undefined} onPress={writable ? () => setEditing(item) : undefined} style={[styles.sprint, { backgroundColor: theme.surface, borderColor: theme.border }]}><View style={[styles.dateIcon, { backgroundColor: theme.surfaceMuted }]}><CalendarRange color={theme.primary} size={20} /></View><View style={styles.flex}><View style={styles.titleLine}><Text numberOfLines={1} style={[styles.sprintName, { color: theme.text }]}>{item.name}</Text><Text style={[styles.status, { color: statusColor(item.status, theme) }]}>{item.status}</Text></View><Text style={[styles.meta, { color: theme.textMuted }]}>{item.start_date} to {item.end_date} · {item.task_count} tasks</Text><View style={[styles.progress, { backgroundColor: theme.surfaceMuted }]}><View style={[styles.progressFill, { backgroundColor: item.progress === 100 ? theme.success : theme.primary, width: `${Math.max(0, Math.min(100, item.progress || 0))}%` }]} /></View></View>{writable ? <Pencil color={theme.textMuted} size={17} /> : null}</Pressable>} /> : null}
    <SprintEditor editing={editing} onClose={() => setEditing(undefined)} onSaved={refresh} projectId={projectId} sheetEnabled={Boolean(project.data?.sheet_integration_enabled && project.data.sheet_id)} />
  </Screen>;
}

function SprintEditor({ editing, onClose, onSaved, projectId, sheetEnabled }: { editing: Sprint | null | undefined; onClose: () => void; onSaved: () => Promise<unknown>; projectId: number; sheetEnabled: boolean }) {
  const theme = useAppTheme();
  const [name, setName] = useState('');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const initialize = () => { setName(editing?.name || ''); setStartDate(editing?.start_date || ''); setEndDate(editing?.end_date || ''); };
  const save = useMutation({ mutationFn: () => { const input = { project_id: projectId, name: name.trim(), start_date: startDate, end_date: endDate }; return editing ? endpoints.updateSprint(editing.id, input) : endpoints.createSprint(input); }, onSuccess: onSaved, onError: (error) => Alert.alert('Unable to save sprint', apiErrorMessage(error)) });
  const remove = useMutation({ mutationFn: () => endpoints.deleteSprint(editing!.id), onSuccess: onSaved, onError: (error) => Alert.alert('Unable to delete sprint', apiErrorMessage(error)) });
  const sheetAction = useMutation({ mutationFn: async (action: 'import' | 'tasks' | 'logs') => { if (action === 'import') await endpoints.importSprintTasks(editing!.id); else if (action === 'tasks') await endpoints.exportSprintTasks(editing!.id); else await endpoints.exportSprintLogs(editing!.id); return action; }, onSuccess: async (action) => { await onSaved(); Alert.alert(action === 'import' ? 'Sprint imported' : 'Sheet updated', action === 'logs' ? 'Task logs were exported to the scheduler sheet.' : 'Sprint tasks were synchronized with the connected sheet.'); }, onError: (error) => Alert.alert('Sheet action failed', apiErrorMessage(error)) });
  return <Modal animationType="slide" onShow={initialize} onRequestClose={onClose} presentationStyle="pageSheet" visible={editing !== undefined}><View style={[styles.modal, { backgroundColor: theme.background }]}><View style={[styles.modalHeader, { borderBottomColor: theme.border }]}><Pressable accessibilityLabel="Close sprint editor" onPress={onClose} style={styles.iconButton}><X color={theme.text} size={22} /></Pressable><Text style={[styles.modalTitle, { color: theme.text }]}>{editing ? 'Sprint settings' : 'New sprint'}</Text><View style={styles.iconButton} /></View><ScrollView contentContainerStyle={styles.form} keyboardShouldPersistTaps="handled"><Field label="Sprint name" value={name} onChangeText={setName} /><View style={styles.columns}><View style={styles.flex}><Field label="Start date" placeholder="YYYY-MM-DD" value={startDate} onChangeText={setStartDate} /></View><View style={styles.flex}><Field label="End date" placeholder="YYYY-MM-DD" value={endDate} onChangeText={setEndDate} /></View></View><PrimaryButton disabled={!name.trim() || !startDate || !endDate} label="Save sprint" loading={save.isPending} onPress={() => save.mutate()} />{editing && sheetEnabled ? <View style={styles.sheetSection}><Text style={[styles.sectionTitle, { color: theme.text }]}>Connected sheet</Text><SheetRow icon={ArrowDownToLine} label="Import sprint tasks" onPress={() => sheetAction.mutate('import')} /><SheetRow icon={ArrowUpFromLine} label="Export sprint tasks" onPress={() => sheetAction.mutate('tasks')} /><SheetRow icon={FileSpreadsheet} label="Export task logs" onPress={() => sheetAction.mutate('logs')} /></View> : null}{editing ? <Pressable onPress={() => Alert.alert(`Delete ${editing.name}?`, 'Tasks in this sprint must be moved or removed first.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => remove.mutate() }])} style={styles.delete}><Trash2 color={theme.danger} size={18} /><Text style={{ color: theme.danger, fontWeight: '800' }}>Delete sprint</Text></Pressable> : null}</ScrollView></View></Modal>;
}

function Field({ label, ...props }: { label: string } & React.ComponentProps<typeof TextInput>) { const theme = useAppTheme(); return <View><Text style={[styles.label, { color: theme.text }]}>{label}</Text><TextInput accessibilityLabel={label} {...props} style={[styles.field, { backgroundColor: theme.surface, borderColor: theme.border, color: theme.text }]} /></View>; }
function SheetRow({ icon: Icon, label, onPress }: { icon: typeof FileSpreadsheet; label: string; onPress: () => void }) { const theme = useAppTheme(); return <Pressable accessibilityRole="button" onPress={onPress} style={[styles.sheetRow, { borderBottomColor: theme.border }]}><Icon color={theme.primary} size={19} /><Text style={[styles.actionTitle, { color: theme.text }]}>{label}</Text><ArrowUpFromLine color={theme.textMuted} size={17} /></Pressable>; }
function statusColor(status: string, theme: ReturnType<typeof useAppTheme>) { if (status === 'completed') return theme.success; if (status === 'running') return theme.primary; return theme.textMuted; }

const styles = StyleSheet.create({ flex: { flex: 1 }, iconButton: { alignItems: 'center', height: 44, justifyContent: 'center', width: 44 }, add: { alignItems: 'center', borderRadius: 8, height: 42, justifyContent: 'center', width: 42 }, sheetAction: { alignItems: 'center', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 11, marginHorizontal: 20, marginTop: 14, minHeight: 62, paddingHorizontal: 13 }, actionTitle: { flex: 1, fontSize: 13, fontWeight: '800' }, actionMeta: { fontSize: 11, marginTop: 3 }, list: { padding: 20, paddingBottom: 44 }, sprint: { alignItems: 'center', borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 11, marginBottom: 9, minHeight: 82, padding: 11 }, dateIcon: { alignItems: 'center', borderRadius: 8, height: 44, justifyContent: 'center', width: 44 }, titleLine: { alignItems: 'center', flexDirection: 'row', gap: 8 }, sprintName: { flex: 1, fontSize: 15, fontWeight: '800' }, status: { fontSize: 9, fontWeight: '900', textTransform: 'uppercase' }, meta: { fontSize: 11, marginTop: 5 }, progress: { borderRadius: 3, height: 6, marginTop: 9, overflow: 'hidden' }, progressFill: { borderRadius: 3, height: 6 }, modal: { flex: 1 }, modalHeader: { alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', justifyContent: 'space-between', minHeight: 62, paddingHorizontal: 10 }, modalTitle: { fontSize: 17, fontWeight: '800' }, form: { gap: 18, padding: 20, paddingBottom: 48 }, columns: { flexDirection: 'row', gap: 10 }, label: { fontSize: 13, fontWeight: '800', marginBottom: 7 }, field: { borderRadius: 8, borderWidth: 1, fontSize: 15, minHeight: 47, paddingHorizontal: 12 }, sheetSection: { marginTop: 6 }, sectionTitle: { fontSize: 16, fontWeight: '800', marginBottom: 8 }, sheetRow: { alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: 11, minHeight: 54 }, delete: { alignItems: 'center', flexDirection: 'row', gap: 8, justifyContent: 'center', minHeight: 48 } });
